#!/bin/bash
# Quick commands for MongoDB management

echo "MongoDB Quick Reference"
echo "======================"
echo ""
echo "Service Management:"
echo "  Start:   brew services start mongodb-community@7.0"
echo "  Stop:    brew services stop mongodb-community@7.0"
echo "  Restart: brew services restart mongodb-community@7.0"
echo "  Status:  brew services list | grep mongodb"
echo ""
echo "MongoDB Shell:"
echo "  Connect: mongosh"
echo "  Use DB:  use ai_code_reviewer"
echo "  Count:   db.code_metadata.countDocuments()"
echo "  Find:    db.code_metadata.find().limit(5).pretty()"
echo "  Exit:    exit"
echo ""
echo "Python Scripts:"
echo "  Setup:      ./setup_mongodb.sh"
echo "  Test:       python src/indexing/test_mongodb.py"
echo "  Build All:  python src/indexing/build_indexes.py"
echo "  Metadata:   python src/indexing/build_indexes.py --skip-indexes"
echo "  Retrieve:   python src/indexing/hybrid_retriever.py --patch 'code'"
echo ""
echo "Data Location:"
echo "  Data:   /usr/local/var/mongodb/"
echo "  Logs:   /usr/local/var/log/mongodb/mongo.log"
echo "  Config: /usr/local/etc/mongod.conf"
echo ""
echo "GUI Tools:"
echo "  Compass: brew install --cask mongodb-compass"
echo "  VS Code: Install 'MongoDB for VS Code' extension"
